# -*- coding: utf-8 -*-
"""gradio.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15I2ftvLaapYyYj-1UeK1gv02tx2bjbxA
"""

# !pip install -q transformers

from transformers import pipeline

ner_pipeline = pipeline("ner", model="RidaDogrul/multilingual-xlm-roberta-for-ner")

text = "I am Tim and I work at Google"

ner_pipeline(text)

text_tr = "Benim adım Ayşe ve Trendyol'da çalışıyorum"
ner_pipeline(text_tr)

ner_pipeline(text_tr, aggregation_strategy = "simple")

def ner(text):
  output = ner_pipeline(text, aggregation_strategy="simple")
  return {"text": text, "entities": output}

# !pip install -q gradio

import gradio as gr

examples = [
    "My name is Tim and I live in California",
    "Ich arbeite bei Google in Berlin",
    "Ayşe, Ankara'lı mı?"
]

demo = gr.Interface(
    ner,
    gr.Textbox(placeholder="Enter sentence here..."),
    gr.HighlightedText(),
    examples=examples
)

demo.launch(share=True)

